version: '3.3'

services:
  phpaddressbook:
    container_name: addressbook_www
    image: php:7.1-apache-stretch
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./data/www:/var/www/html/
    command: >
      sh -c "docker-php-ext-install mysqli
      && apt-get update
      && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
      && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      && docker-php-ext-install -j$$(nproc) gd
      && apache2-foreground
      "
  db:
    container_name: addressbook_db
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: addressbook
      MYSQL_USER: addressbook
      MYSQL_PASSWORD: addressbook
      MYSQL_ROOT_PASSWORD: addressbook
    volumes:
      - ./data/mysql/:/var/lib/mysql 
